apiVersion: v1
kind: Service
metadata:
  name: atlas-pg
  namespace: atlas-pg
  annotations:
    tailscale.com/hostname: atlas-pg # Machine name in the tailnet
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: atlas-pg
    app.kubernetes.io/name: postgresql
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: 5432
