apiVersion: v1
kind: Service
metadata:
  name: signoz-dev
  namespace: signoz
  annotations:
    tailscale.com/hostname: signoz-dev # Machine name in the tailnet
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/component: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: signoz-otel-dev
  namespace: signoz
  annotations:
    tailscale.com/hostname: signoz-otel-dev # Machine name in the tailnet
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
  ports:
    - name: jaeger-grpc
      port: 14250
      protocol: TCP
      targetPort: jaeger-grpc
    - name: jaeger-thrift
      port: 14268
      protocol: TCP
      targetPort: jaeger-thrift
    - name: logsheroku
      port: 8081
      protocol: TCP
      targetPort: logsheroku
    - name: logsjson
      port: 8082
      protocol: TCP
      targetPort: logsjson
    - name: metrics
      port: 8888
      protocol: TCP
      targetPort: metrics
    - name: otlp
      port: 4317
      protocol: TCP
      targetPort: otlp
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: otlp-http
